Bag of Words

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
doc1 = "The weather in Rotkreuz is nice. Rotkreuz is big."
doc2 = "The campus is in Rotkreuz"
doc3= "The Department of Informatics at Hochschule Luzern"

In [3]:
documents = [doc1,doc2,doc3]

In [4]:
vectorizer = CountVectorizer()

In [6]:
print(vectorizer.fit_transform(documents))

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 19 stored elements and shape (3, 14)>
  Coords	Values
  (0, 12)	1
  (0, 13)	1
  (0, 5)	1
  (0, 11)	2
  (0, 7)	2
  (0, 9)	1
  (0, 1)	1
  (1, 12)	1
  (1, 5)	1
  (1, 11)	1
  (1, 7)	1
  (1, 2)	1
  (2, 12)	1
  (2, 3)	1
  (2, 10)	1
  (2, 6)	1
  (2, 0)	1
  (2, 4)	1
  (2, 8)	1

In [5]:
print(vectorizer.fit_transform(documents).todense())

print(vectorizer.vocabulary_)

[[0 1 0 0 0 1 0 2 0 1 0 2 1 1]
 [0 0 1 0 0 1 0 1 0 0 0 1 1 0]
 [1 0 0 1 1 0 1 0 1 0 1 0 1 0]]
{'the': 12, 'weather': 13, 'in': 5, 'rotkreuz': 11, 'is': 7, 'nice': 9, 'big': 1, 'campus': 2, 'department': 3, 'of': 10, 'informatics': 6, 'at': 0, 'hochschule': 4, 'luzern': 8}

Cosine Similarity

In [8]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

doc1 = "I like movies with a lot of action."
doc2 = "I like movies with a lot of action."
doc3 = " I hate movies with a romantic touch."

documents = [doc1, doc2, doc3]

In [9]:
count_vectorizer = CountVectorizer(stop_words='english')
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(documents)

In [10]:
print(sparse_matrix.todense())
print(count_vectorizer.get_feature_names_out())

[[1 0 1 1 1 1 0 0 1]
 [1 0 1 1 1 1 0 0 1]
 [0 1 0 0 1 0 1 1 1]]
['action' 'hate' 'like' 'lot' 'movies' 'of' 'romantic' 'touch' 'with']

In [11]:
count_vectorizer_all = CountVectorizer(token_pattern=r"(?u)\b\w+\b")
sparse_matrix_all = count_vectorizer_all.fit_transform(documents)

print(count_vectorizer_all.get_feature_names_out())

['a' 'action' 'hate' 'i' 'like' 'lot' 'movies' 'of' 'romantic' 'touch'
 'with']

In [12]:
count_vectorizer_stop = CountVectorizer(stop_words='english')
sparse_matrix_stop = count_vectorizer_stop.fit_transform(documents)

print(count_vectorizer_stop.get_feature_names_out())

['action' 'hate' 'like' 'lot' 'movies' 'romantic' 'touch']

In [13]:
df = pd.DataFrame(
    sparse_matrix_stop.todense(), 
    columns=count_vectorizer_stop.get_feature_names_out(), 
    index=['doc1', 'doc2', 'doc3']
)
df

      action  hate  like  lot  movies  romantic  touch
doc1       1     0     1    1       1         0      0
doc2       1     0     1    1       1         0      0
doc3       0     1     0    0       1         1      1

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

print(cosine_similarity(df, df))

[[1.   1.   0.25]
 [1.   1.   0.25]
 [0.25 0.25 1.  ]]

TF-IDF with Sklearn

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer 

doc1 = "I like movies."
doc2 = "Movies are fun."
doc3 = "Movies are cool."

In [17]:
documents = [doc1, doc2, doc3]

In [18]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(documents)

In [19]:
print(result)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8 stored elements and shape (3, 5)>
  Coords	Values
  (0, 3)	0.8610369959439764
  (0, 4)	0.5085423203783267
  (1, 4)	0.4254405389711991
  (1, 0)	0.5478321549274363
  (1, 2)	0.7203334490549893
  (2, 4)	0.4254405389711991
  (2, 0)	0.5478321549274363
  (2, 1)	0.7203334490549893

In [20]:
print('\nWord indexes:')
print(tfidf.vocabulary_)

Word indexes:
{'like': 3, 'movies': 4, 'are': 0, 'fun': 2, 'cool': 1}

In [21]:
tfidf.get_feature_names_out()

array(['are', 'cool', 'fun', 'like', 'movies'], dtype=object)

In [22]:
tfidf.vocabulary_

{'like': 3, 'movies': 4, 'are': 0, 'fun': 2, 'cool': 1}

In [23]:
print('\nidf values:')
for ele1, ele2 in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    print(ele1, ':', ele2)

idf values:
are : 1.2876820724517808
cool : 1.6931471805599454
fun : 1.6931471805599454
like : 1.6931471805599454
movies : 1.0

In [25]:
print(result.toarray())

[[0.         0.         0.         0.861037   0.50854232]
 [0.54783215 0.         0.72033345 0.         0.42544054]
 [0.54783215 0.72033345 0.         0.         0.42544054]]

In [26]:
print('\ntf-idf values in matrix form:')
print(result.toarray())

tf-idf values in matrix form:
[[0.         0.         0.         0.861037   0.50854232]
 [0.54783215 0.         0.72033345 0.         0.42544054]
 [0.54783215 0.72033345 0.         0.         0.42544054]]

In [29]:
df = pd.DataFrame(
    result.toarray(), 
    columns=tfidf.get_feature_names_out(), 
    index=['doc1', 'doc2', 'doc3']
)

In [30]:
df

           are      cool       fun      like    movies
doc1  0.000000  0.000000  0.000000  0.861037  0.508542
doc2  0.547832  0.000000  0.720333  0.000000  0.425441
doc3  0.547832  0.720333  0.000000  0.000000  0.425441